version: "3"

services:
  api-gateway:
    build: .
    command: nodemon -L index.js
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      - URL_SERVER_ACCOUNT=localhost:3003/v1
      - URL_SERVER_CONTACT=localhost:3002/v1